name: ConditionalCommands
author: konsolas
description: ${project.description}
website: ${project.url}

version: ${project.version}
main: me.konsolas.conditionalcommands.ConditionalCommands
softdepend: [AAC]

commands:
  ccmd:
    usage: /<command> <mode> [args...]
    aliases: [cc]
    description: The main command for ConditionalCommands.
    permission: cc.use

permissions:
  cc.use:
    description: Grants access to the root of ConditionalCommands.
    default: op